### ISSUE TITLE
New combinations

### ISSUE THREAD

**Issue by ulamnet** [chunyenHuang/trand#55]
Hello , ı want to create new combinations but ı don't see any clothing in this part. see : 

![ekran alintisi](https://cloud.githubusercontent.com/assets/583003/15574516/7e8a6fe4-2356-11e6-9e0e-20d272e56122.PNG)

**Comment by chunyenHuang** [comment]
Hello ulamnet,
Thanks for using and report.
For empty combination, you may go to "Search" tab and add something to your collections first. You can only make combinations with your collections.
You may use this test account:
ID: test@gmail.com
PW: test

I am sorry that I didn't write tutorial for navigation. I will do it soon!
Thanks again.

**Comment by ulamnet** [comment]
thanks for this!
